### ISSUE TITLE
Step 1 - Missing data-connectors directory

### ISSUE THREAD

**Issue by kevindavi5** [hydrateio/advanced-graphql-server-tutorial#14]
In the Use SQL for Data section it wants us to import mysqlDataConnector from a folder that doesn’t exist in the step-0 branch. 

I would suggest two options: 
1. adding instructions to create the data-connectors folder and include a snippet for the mysql.js file.
2. adding the data-connectors folder to step-0 as part of the foundation the user can build upon.

**Comment by natergj** [comment]
the step 1 instructions do include a section about the data connector that links to the completed mysql connector file in the step 1 branch. https://github.com/hydrateio/advanced-graphql-server-tutorial/blame/step-1-add-mysql-connection/docs/_pages/1.add-sql.md#L27
Would it be useful to include the entire code snippet in the docs instead of a link to the completed file? 

Another option may be to rewrite the commit history and add a separate commit that only adds the MySQL connector, users could check out that commit.

My thoughts were that each branch would be the completed code for each step. Since step 0 hasn't gotten to the SQL part yet, I'd rather not add the code file there.
